'use client';
import {useState} from 'react';
const interests=['🐘 Animals','🚀 Space','🌊 Ocean','🌱 Nature','🔬 Science','🦖 Dinosaurs','🚗 Vehicles','🎨 Art'];
export default function Home(){
 const [step,setStep]=useState(0); const [name,setName]=useState('Chloe'); const [age,setAge]=useState(4); const [selected,setSelected]=useState(['🐘 Animals','🚀 Space','🔬 Science']);
 if(step===0)return <main><section className="hero"><div className="globe">🌎</div><p className="eyebrow">LITTLE WORLD</p><h1>Big world.<br/>Little ears.</h1><p className="lead">A personalized 3-minute daily audio show that helps your child discover what’s happening in the world.</p><button onClick={()=>setStep(1)}>Create their Little World →</button><div className="preview"><small>TODAY’S ADVENTURE</small><h3>Singapore → Africa → Space</h3><p>🌫️ Hazy skies &nbsp; 🐕 Wild dogs &nbsp; 🚀 Plant-watching satellites</p></div></section></main>;
 if(step===1)return <main><section><button className="back" onClick={()=>setStep(0)}>← Back</button><p className="eyebrow">LET’S GET STARTED</p><h2>Who are we making<br/>Little World for?</h2><label>Child’s name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Age</label><div className="ages">{[3,4,5,6,7].map(a=><button className={age===a?'active':''} onClick={()=>setAge(a)} key={a}>{a}</button>)}</div><label>What makes {name||'them'} curious?</label><div className="chips">{interests.map(i=><button key={i} className={selected.includes(i)?'active':''} onClick={()=>setSelected(s=>s.includes(i)?s.filter(x=>x!==i):[...s,i])}>{i}</button>)}</div><button onClick={()=>setStep(2)}>Create {name||'their'}’s Little World →</button></section></main>;
 return <main><section><div className="top"><div><p className="eyebrow">GOOD MORNING</p><h2>{name}! ☀️</h2></div><div className="avatar">{name[0]||'L'}</div></div><div className="cover"><span>🌎</span><small>{name.toUpperCase()}’S</small><h2>LITTLE<br/>WORLD</h2><p>Singapore → Africa → Space</p></div><div className="player"><button className="play">▶</button><div><strong>Today’s Little World</strong><p>3:42 · Wednesday, September 16</p><div className="bar"><i/></div></div></div><div className="stories"><p>🇸🇬 <b>Close to Home</b><br/><span>Why Singapore’s sky looked hazy</span></p><p>🐕 <b>Our Big World</b><br/><span>Meet some extraordinary travelling wild dogs</span></p><p>🚀 <b>Amazing Discovery</b><br/><span>A satellite that can see plants glow</span></p></div><div className="question"><small>💭 QUESTION OF THE DAY</small><h3>If you could send your own satellite into space, what would you ask it to look after?</h3><p>Talk about it together ❤️</p></div><nav><b>◉<small>Today</small></b><span>▤<small>Library</small></span><span>☺<small>Profile</small></span></nav></section></main>;
}
